import { Arac } from './supabase'

export const mockAraclar: Arac[] = [
  {
    id: '1',
    slug: 'bmw-320i-2021',
    marka: 'BMW',
    model: '320i',
    yil: 2021,
    fiyat: 1_850_000,
    km: 42000,
    yakit: 'Benzin',
    vites: 'Otomatik',
    renk: 'Beyaz',
    aciklama: 'Hasar kayıtsız, tramer yok. Servis bakımlı, özgün boyalı araç. Elektrikli cam, ısıtmalı deri koltuk, geri görüş kamerası, park sensörü, sunroof mevcut.',
    ozellikler: ['Sunroof', 'Deri Koltuk', 'Geri Görüş Kamerası', 'Park Sensörü', 'Navigasyon', 'Isıtmalı Koltuk'],
    fotograflar: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
      'https://images.unsplash.com/photo-1617531653332-bd46c16f4d68?w=800&q=80',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    ],
    kampanya: true,
    kampanya_etiketi: 'Fiyat Düştü',
    aktif: true,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    slug: 'mercedes-c180-2020',
    marka: 'Mercedes',
    model: 'C180',
    yil: 2020,
    fiyat: 2_100_000,
    km: 58000,
    yakit: 'Benzin',
    vites: 'Otomatik',
    renk: 'Gri',
    aciklama: 'Avantgarde paketi, AMG line dış görünüm. Bakımlar yapılmış, tek elden çıkma, tramer yok.',
    ozellikler: ['AMG Paket', 'Panoramik Cam Tavan', 'Burmester Ses', 'Hafıza Koltuk', '360° Kamera'],
    fotograflar: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
    ],
    kampanya: false,
    kampanya_etiketi: null,
    aktif: true,
    created_at: '2024-02-01',
  },
  {
    id: '3',
    slug: 'toyota-corolla-2022',
    marka: 'Toyota',
    model: 'Corolla',
    yil: 2022,
    fiyat: 1_150_000,
    km: 28000,
    yakit: 'Hibrit',
    vites: 'Otomatik',
    renk: 'Kırmızı',
    aciklama: 'Hybrid teknoloji, yakıt tasarrufu maksimum. Bakım anlaşmalı, garanti devam ediyor.',
    ozellikler: ['Hibrit Motor', 'Toyota Safety Sense', 'Wireless Şarj', 'Apple CarPlay'],
    fotograflar: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    ],
    kampanya: true,
    kampanya_etiketi: 'Hızlı Satış',
    aktif: true,
    created_at: '2024-02-10',
  },
  {
    id: '4',
    slug: 'volkswagen-passat-2019',
    marka: 'Volkswagen',
    model: 'Passat',
    yil: 2019,
    fiyat: 980_000,
    km: 89000,
    yakit: 'Dizel',
    vites: 'Otomatik',
    renk: 'Siyah',
    aciklama: 'Elegance paket, panoramik tavan, dijital gösterge paneli. Temiz araç.',
    ozellikler: ['Panoramik Tavan', 'Dijital Gösterge', 'Adaptif Hız Sabitleyici', 'Lane Assist'],
    fotograflar: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80',
    ],
    kampanya: false,
    kampanya_etiketi: null,
    aktif: true,
    created_at: '2024-01-20',
  },
  {
    id: '5',
    slug: 'audi-a4-2021',
    marka: 'Audi',
    model: 'A4',
    yil: 2021,
    fiyat: 2_350_000,
    km: 35000,
    yakit: 'Benzin',
    vites: 'Otomatik',
    renk: 'Mavi',
    aciklama: 'S-Line dış paket, Virtual Cockpit, Bang & Olufsen ses sistemi. Özgün durumda.',
    ozellikler: ['S-Line Paket', 'Virtual Cockpit', 'Bang & Olufsen', 'Matrix LED', 'Isıtmalı Direksiyon'],
    fotograflar: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    ],
    kampanya: false,
    kampanya_etiketi: null,
    aktif: true,
    created_at: '2024-03-01',
  },
  {
    id: '6',
    slug: 'honda-civic-2023',
    marka: 'Honda',
    model: 'Civic',
    yil: 2023,
    fiyat: 1_320_000,
    km: 12000,
    yakit: 'Benzin',
    vites: 'Otomatik',
    renk: 'Beyaz',
    aciklama: 'Sıfır gibi, garanti devam ediyor. Herhangi bir hasar yok.',
    ozellikler: ['Honda Sensing', 'Wireless CarPlay', 'LED Matrix Far', 'Bose Ses Sistemi'],
    fotograflar: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    ],
    kampanya: true,
    kampanya_etiketi: 'Yeni Eklendi',
    aktif: true,
    created_at: '2024-03-15',
  },
]

export const markalar = [...new Set(mockAraclar.map(a => a.marka))].sort()
export const yakitTipleri = [...new Set(mockAraclar.map(a => a.yakit))].sort()
export const vitesTipleri = [...new Set(mockAraclar.map(a => a.vites))].sort()
